### ISSUE TITLE
can i create a server for wiregaurd with authentication with this code? and how?

### ISSUE THREAD

**Issue by sajadabasi** [mullvad/wg-manager#14]
can i create a server for wiregaurd with authentication with this code? and how? i see syncing public keys but i don't understand the rest can you explain?
thanks

**Comment by DMarby** [comment]
We don't provide support for how to use this, sorry.
You can see what kind of data structure it expects from the API in the tests, eg https://github.com/mullvad/wg-manager/blob/master/api/api_test.go#L15

**Comment by sajadabasi** [comment]
thanks for your fast reply.
I've read the code but i do have some question I'd be thankful if you answer them.
What is `allowedIPs` in code and `IPv4` `IPv6` in API I don't understand it's use?
how this code detects user is connected and avoid from connecting concurrent 5 users?
Thanks you.
