### ISSUE TITLE
how detects 5 users are connected, and what's `allowedIPs`? 

### ISSUE THREAD

**Issue by sajadabasi** [mullvad/wg-manager#15]
I've read the code but i do have some question I'd be thankful if you answer them.
What is `allowedIPs` in code and `IPv4` `IPv6` in API I don't understand it's use?
how this code detects user is connected and avoid from connecting concurrent 5 users?
Thanks you so much.

**Comment by DMarby** [comment]
As mentioned previously, we don't provide support for this repository.
